@user = User.create(email: 'kaylas.email.address@gmail.com',
                      password: 'password',
                      password_confirmation: 'password')


@project1 = Project.create(title: 'The Webby Awards',
                            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur auctor sodales mauris sit amet mollis. Curabitur iaculis volutpat neque eget dignissim. Morbi blandit et purus nec egestas. Quisque ullamcorper urna scelerisque purus convallis, sit amet volutpat purus pharetra. Fusce ac justo accumsan, interdum nunc quis, facilisis velit. Praesent vitae iaculis enim, eget porttitor sapien. Maecenas varius finibus eros eget varius. Duis vehicula ex      neque, volutpat iaculis libero iaculis et. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc in iaculis sem. Curabitur at pharetra magna, quis consectetur risus. Integer auctor eleifend finibus. Maecenas tempus tristique arcu at egestas. Nulla vitae commodo nulla. Fusce ac est arcu.')

@project2 = Project.create(title: 'Cancercare',
                            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur auctor sodales mauris sit amet mollis. Curabitur iaculis volutpat neque eget dignissim. Morbi blandit et purus nec egestas. Quisque ullamcorper urna scelerisque purus convallis, sit amet volutpat purus pharetra. Fusce ac justo accumsan, interdum nunc quis, facilisis velit. Praesent vitae iaculis enim, eget porttitor sapien. Maecenas varius finibus eros eget varius. Duis vehicula ex      neque, volutpat iaculis libero iaculis et. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc in iaculis sem. Curabitur at pharetra magna, quis consectetur risus. Integer auctor eleifend finibus. Maecenas tempus tristique arcu at egestas. Nulla vitae commodo nulla. Fusce ac est arcu.')

@project3 = Project.create(title: 'Backher',
                            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur auctor sodales mauris sit amet mollis. Curabitur iaculis volutpat neque eget dignissim. Morbi blandit et purus nec egestas. Quisque ullamcorper urna scelerisque purus convallis, sit amet volutpat purus pharetra. Fusce ac justo accumsan, interdum nunc quis, facilisis velit. Praesent vitae iaculis enim, eget porttitor sapien. Maecenas varius finibus eros eget varius. Duis vehicula ex      neque, volutpat iaculis libero iaculis et. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc in iaculis sem. Curabitur at pharetra magna, quis consectetur risus. Integer auctor eleifend finibus. Maecenas tempus tristique arcu at egestas. Nulla vitae commodo nulla. Fusce ac est arcu.')

@project4 = Project.create(title: 'Portfolio',
                          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur auctor sodales mauris sit amet mollis. Curabitur iaculis volutpat neque eget dignissim. Morbi blandit et purus nec egestas. Quisque ullamcorper urna scelerisque purus convallis, sit amet volutpat purus pharetra. Fusce ac justo accumsan, interdum nunc quis, facilisis velit. Praesent vitae iaculis enim, eget porttitor sapien. Maecenas varius finibus eros eget varius. Duis vehicula ex      neque, volutpat iaculis libero iaculis et. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc in iaculis sem. Curabitur at pharetra magna, quis consectetur risus. Integer auctor eleifend finibus. Maecenas tempus tristique arcu at egestas. Nulla vitae commodo nulla. Fusce ac est arcu.')
